#!/bin/bash

# scripts
killall -q sxhkd; sxhkd &
killall -q redshift; redshift &
killall -q dunst; dunst &
killall -q picom; picom --config ~/.config/picom/picom.conf -b
dropbox stop; sleep 1; dropbox start &
~/.fehbg &
~/.config/polybar/launch.sh &
xset s off # screensaver

# settings
# bspc monitor HDMI-1 -d home web terminal code chat music video files misc
bspc monitor DP-0 -d home web terminal code chat music video files misc

bspc config border_width               2
bspc config window_gap                 8
bspc config top_padding                32
bspc config borderless_monocle         true
bspc config gapless_monocle            false
bspc config single_monocle             true
bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true

bspc config presel_feedback_color      "#DADBC0"
bspc config active_border_color        "#DADBC0"
bspc config focused_border_color       "#DADBC0"
bspc config normal_border_color        "#1f2430"

bspc desktop web --layout monocle
bspc desktop chat --layout monocle
bspc desktop music --layout monocle
bspc desktop video --layout monocle

bspc rule -a Firefox desktop=web follow=on
bspc rule -a Alacritty desktop=terminal follow=on
bspc rule -a Code desktop=code follow=on
bspc rule -a Slack desktop=chat follow=on
bspc rule -a discord desktop=chat follow=on
bspc rule -a spotify desktop=music follow=on
bspc rule -a vlc desktop=video follow=on
bspc rule -a Org.gnome.Nautilus desktop=files follow=on
bspc rule -a KeePassXC desktop=misc state=floating follow=on
bspc rule -a "TeamSpeak 3" desktop=misc state=floating follow=on
bspc rule -a Lutris desktop=misc follow=on
bspc rule -a Steam desktop=misc state=floating follow=on
