# exports
source ~/.exports

# custom aliases
source ~/.aliases

# antigen
source ~/.antigen/config

# load fzf
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

# load asdf
source ~/.asdf/asdf.sh

fpath=($HOME/.asdf/completions $fpath)
autoload -Uz compinit
if [[ -n ~/.zcompdump(#qN.mh+24) ]]; then
  compinit;
else
  compinit -C;
fi;

# fortune!
if [ -x /usr/bin/fortune ] ; then
    echo
    /usr/bin/fortune
fi

eval $(keychain --eval --quiet id_rsa)
